FROM 049843000081.dkr.ecr.us-east-1.amazonaws.com/cruddur-python:3.10-slim-buster


# For debugging, do not put in prod image
# RUN apt-get update -y
# UN apt-get install inputils-ping -y


WORKDIR /backend-flask

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE ${PORT}
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567", "--no-debugger", "--no-reload", "--no-debug"]