openapi: '3.0.2'
info:
  title: Cruddur Backend API
  version: '1.0'
    
servers:
  - url: https://api.server.test/v1
paths:
  /api/activities/home:
    get:
      description: ''
      responses:
        '200':
          description: OK

  /api/activities/search:
    get:
      description: ''
      responses:
        '200':
          description: OK
  /api/activities:
    post:
      responses:
        '200':
          description: OK
  /api/activities/@{handle}:
    get:
      description: ''
      responses:
        '200':
          description: OK
  /api/message_groups:
    get:
      description: ''
      responses:
        '200':
          description: Returns an array of messages groups for a specific user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageGroups'
  /api/messages/@{handle}:
    get:
      description: 'Returns private communication between two users'
      responses:
        '200':
          description: Returns an array of messages between two users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Messages'
  /api/messages:
    post:
      description: 'Create a direct message between two users'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_receiver_handle:
                  type: string
      responses:
        '200':
          description: Return a single message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

components:
  schemas:
    Activity:
      type: object
      properties:
        uuid:
          type: string
          example: 0056a369-4618-43a4-ad88-e7c371bf5582
        display_name:
          type: string
          example: "Andrew Brown"
        handle:
          type: string
          example: "andrewbrown"
        message:
          type: string
          example: "Who likes pineapple on their pizza?"
        created_at:
          type: string
          example: "2021-07-27T16:02:08.070557"
        expires_at:
          type: string
          example: "2021-07-27T16:02:08.070557"

    Message:
      type: object
      properties:
        uuid:
          type: string
          example: 0056a369-4618-43a4-ad88-e7c371bf5582
        display_name:
          type: string
          example: "Andrew Brown"
        handle:
          type: string
          example: "andrewbrown"
        message:
          type: string
          example: "Who likes pineapple on their pizza?"
        created_at:
          type: string
          example: "2021-07-27T16:02:08.070557"
    Messages:
      type: array
      properties:
        items:
          $ref: '#/components/schemas/Message'
    MessageGroup:
      type: object
      properties:
        uuid:
          type: string
          example: 0056a369-4618-43a4-ad88-e7c371bf5582
        display_name:
          type: string
          example: "Worf"
        handle:
          type: string
          example: "worf"
    MessageGroups:
      type: array
      properties:
        items:
          type: object
          properties:
            items:
              $ref: '#/components/schemas/MessageGroup'