#! /usr/bin/env bash
set -e # stop the execution of the script if it fails

CONFIG_PATH="/workspaces/aws-bootcamp-cruddur-2023/ddb/config.toml"
PACKAGED_TEMPLATE_FILE='/workspaces/aws-bootcamp-cruddur-2023/.aws-sam/build/packaged.yaml'

echo "== deploy"
sam deploy \
--template-file $PACKAGED_TEMPLATE_FILE \
--stack-name "CrdDdb" \
--config-file $CONFIG_PATH \
--tags group=cruddur-ddb \
--no-execute-changeset \
--capabilities CAPABILITY_NAMED_IAM